// src/pages/RocketList.tsx
import { useEffect, useMemo, useState } from 'react'
import { useRocketStore } from '../store/rocketStore'
import type { Rocket } from '../types/rocket.ts'
import Loading from '../components/Loading.tsx'
import ErrorState from '../components/ErrorState.tsx'
import RocketCard from '../components/RocketCard.tsx'
import Header from '../components/Header.tsx'

const RocketList = () => {
    const { rockets, loading, error, getRockets, addRocket } = useRocketStore()
    const [filter, setFilter] = useState('')

    useEffect(() => {
        if (rockets.length === 0) {
            getRockets()
        }
    }, [rockets.length, getRockets])

    const filteredRockets = useMemo(() => {
        return rockets.filter((rocket) =>
            rocket.name.toLowerCase().includes(filter.toLowerCase())
        )
    }, [rockets, filter])

    const handleAddRocket = () => {
        const newRocket: Rocket = {
            id: crypto.randomUUID(),
            name: 'My Custom Rocket',
            description: 'This is a custom rocket added locally',
            country: 'Indonesia',
            cost_per_launch: 0,
            first_flight: '2025-01-01',
            flickr_images: [],
        }

        addRocket(newRocket)
    }

    if (loading) return <Loading />

    if (error) return <ErrorState message={error} onRetry={getRockets} />

    return (
        <div>
            <Header />
            <input
                type="text"
                placeholder="Filter rocket by name"
                value={filter}
                onChange={(e) => setFilter(e.target.value)}
            />

            <button onClick={handleAddRocket}>Add Rocket</button>

            <ul>
                {filteredRockets.map((rocket) => (
                    <RocketCard key={rocket.id} rocket={rocket} />
                ))}
            </ul>
        </div>
    )
}

export default RocketList

// src/pages/RocketList.vue
<template>
  <div>
    <h1>SpaceX Rockets</h1>
    <RocketFilter @filter="setFilter" />
    <Loading v-if="loading" />
    <ErrorRetry v-if="error" @retry="fetchData" />
    <div v-if="!loading && !error">
      <RocketCard
        v-for="rocket in filteredRockets"
        :key="rocket.id"
        :rocket="rocket"
      />
    </div>
    <button @click="addFakeRocket">Add Rocket</button>
  </div>
</template>

<script setup lang="ts">
import { onMounted, ref, computed } from "vue";
import { useRocketStore } from "../stores/rocketStore";
import RocketCard from "../components/RocketCard.vue";
import RocketFilter from "../components/RocketFilter.vue";
import Loading from "../components/Loading.vue";
import ErrorRetry from "../components/ErrorRetry.vue";

const store = useRocketStore();
const filter = ref("");

onMounted(() => store.fetchRockets());

const setFilter = (val: string) => {
  filter.value = val;
};

const filteredRockets = computed(() =>
  store.rockets.filter((r: any) =>
    r.name.toLowerCase().includes(filter.value.toLowerCase())
  )
);

const fetchData = () => store.fetchRockets();
const addFakeRocket = () => {
  store.addRocket({
    id: Math.random().toString(36),
    name: "New Rocket",
    description: "Added locally",
    flickr_images: [""],
    country: "",
    cost_per_launch: 0,
    first_flight: "",
  });
};
</script>
