// src/components/layouts/Header.vue
<template>
  <v-container fluid class="pa-0">
    <header class="w-full bg-white flex justify-between px-10 py-4">
      <span class="font-bold text-lg text-gray-700">🚀 Rocket Apps</span>
      <span class="font-bold text-lg text-gray-700">Testing</span>
    </header>
  </v-container>
</template>

<script setup lang="ts"></script>

// src/components/Header.tsx
const Header = () => {
    return (
        <div className="bg-purple-100 lg:flex lg:items-center lg:justify-between p-4 mb-5">
            <div className="min-w-0 flex-1">
                <h2 className="text-2xl/7 font-bold text-purple-900 sm:truncate sm:text-3xl sm:tracking-tight">
                    My Rockets 🚀
                </h2>
            </div>
        </div>
    )
}

export default Header
